Repository ivandi1980/my-fastapi, pull requests merged in 2022-06, with the labels that each got.

#1 README.MD was added
  README.md
Labels: documentation, enhancement

#2 models was added
  main.py
  models.py
Labels: enhancement

#3 modified main
  main.py
Labels: bug, enhancement

#4 Models updated!!
  main.py
  models.py
Labels: bug, enhancement

#5 docs updated
  README.md
  captured/redoc.png
  captured/swagger.png
Labels: documentation, enhancement

#6 added edit user
  main.py
  models.py
Labels: enhancement

#7 adding docker
  .gitignore
  Dockerfile
  README.md
  captured/redoc.png
  captured/swagger.png
Labels: bug, documentation, enhancement
